# This file was generated by GoReleaser. DO NOT EDIT.
cask "zavudev" do
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/zavudev/cli/releases/download/v#{version}/zavudev_#{version}_macos_amd64.zip"
      sha256 "459ada8ab916b1cad0d478b233d0f0dfd1d8c7c768f64e925c53daa9a6da514f"
    end
    on_arm do
      url "https://github.com/zavudev/cli/releases/download/v#{version}/zavudev_#{version}_macos_arm64.zip"
      sha256 "11f07a0f45dffa7b2998016d23e2ba968ddf2b53916eee06a035d117345cbce5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/zavudev/cli/releases/download/v#{version}/zavudev_#{version}_linux_amd64.tar.gz"
      sha256 "23333c75fc795565164f5f3d1828ccad4ec251719b64e4835a6e36f4f3c73d0e"
    end
    on_arm do
      url "https://github.com/zavudev/cli/releases/download/v#{version}/zavudev_#{version}_linux_arm64.tar.gz"
      sha256 "0d632abff649f26485b236555e76e1cfc6749647f10e8f8bb40147bb22364b3d"
    end
  end

  name "zavudev"
  desc "The official CLI for Zavu.dev"
  homepage "https://github.com/zavudev/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "zavudev"
  manpage "man/man1/zavudev.1.gz"
  bash_completion "completions/zavudev.bash"
  fish_completion "completions/zavudev.fish"
  zsh_completion "completions/zavudev.zsh"

  # No zap stanza required

end
